-- Interactive Rocq (Coq) proofs: Coqtail (2026-09-10, user request).
--
-- Rocq is the one language here that is not edited so much as *executed*. A
-- proof is a sequence of tactics, each transforming a goal state, and the
-- question while writing one is always "what is the goal right now" - which no
-- amount of syntax highlighting answers. Coqtail runs a Rocq process, feeds it
-- the buffer one sentence at a time under your control, and shows the
-- resulting goals and messages in two side panels.
--
-- Chosen over the LSP route deliberately. coq-lsp exists and is installed in
-- the opam switch, and the rest of this config would have preferred it -
-- same keys as the other twenty servers, diagnostics through the same
-- pipeline. Two things decided against it:
--
--   * Continuous checking re-verifies the file on every edit. A single Qed can
--     take seconds; step-through only checks as far as you have gone, which is
--     why most Coq work is still done that way rather than out of nostalgia.
--   * coq-lsp's own capability table still answers "No" to references, code
--     actions, semantic tokens and inlay hints, so the LSP integration would
--     have bought less uniformity than it looks like from the outside.
--
-- Requirements, all already satisfied on this machine:
--
--   * Python 3 with pynvim - Coqtail's engine is Python, talking to Neovim
--     through the python3 provider (`:checkhealth provider` shows it).
--   * `coqidetop` on PATH - NOT part of the `rocq` binary. Rocq speaks its
--     IDE protocol through a separate XML server, packaged in opam as
--     `coqide-server`; `rocq` itself has no ide subcommand. Coqtail launches
--     `coqidetop` by name (its python/xmlInterface.py), so without that
--     package it fails at startup with nothing obviously wrong in the config.
--
-- No lazy-load trigger. Coqtail ships the ftdetect, syntax and indent files
-- for Rocq as well as the proof interface, and those have to be in place
-- before the first .v buffer is read rather than after it.
--
-- Filetype note: ".v" is claimed by Verilog, Rocq and V alike. This config
-- used to map it to Verilog outright; that override was removed in
-- lua/jwa/lsp/init.lua so Neovim's own content-based detector can decide, and
-- the comment there explains what it looks at.
--
-- coqtail_noimap (2026-09-13). Coqtail installs its default mappings under
-- `g:coqtail_map_prefix`, which defaults to "<leader>c" (autoload/coqtail.vim,
-- in coqtail#define_mappings) - and <leader> is SPACE here, set in
-- jwa/init.lua. Nine of its commands are mapped in INSERT mode as well as
-- normal - Next, Undo, ToLine, ToTop, JumpToEnd, JumpToError, RestorePanels,
-- GotoGoalStart, GotoGoalEnd - so every .v buffer carried `imap <buffer>
-- <Space>cj` and eight siblings.
--
-- The consequence is that a space typed in insert mode is the prefix of nine
-- mappings, so Vim waits the full 'timeoutlen' (1000ms, never overridden in
-- this config) before committing it: every space in a proof stalled about a
-- second. It is invisible to `:profile` because nothing runs during the stall
-- - Vim is waiting for the next key, not executing anything - and unaffected
-- by turning off syntax, indent, matchparen, conceal or the completion engine,
-- which is what made it expensive to find.
--
-- Switched off rather than re-prefixed: stepping a proof from insert mode is
-- not something anyone does, and dropping the insert half leaves every normal-
-- and visual-mode key in docs/keymappings/lsp/rocq.md exactly as documented.
--
-- Third time a plugin's default prefix has collided with the space leader
-- here; see the same note on plugins/spec/ocaml.lua and plugins/spec/lisp.lua.
return {
	"whonore/Coqtail",
	init = function()
		vim.g.coqtail_noimap = 1
	end,
}
